jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cryptobank
    password: bLG1Z0@5cXxjsv
    username: cryptobank
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect